<?php
/**
 * @copyright Copyright (c) 2016 www.magebuzz.com
 */
$deal = $block->getDeal();
if ($deal->getId()) {
    $helper = $block->getHelper();
    ?>
    <div class="content-header">
        <table cellspacing="0">
            <tbody>
                <tr>
                    <td>
                        <h3 class="icon-head head-adminhtml-dailydeal">Deal Report: <?php echo $deal->getTitle(); ?></h3>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
    <div class="deal-report-annotation" style="width: 30%; float:right; margin-bottom:20px;">
        <div>
            <div class="annotation-color" style="background-color:#f5d8d7; width:30px; height:20px; float:left;"></div>
            <b>&nbsp;<?php echo __('Period of Deal'); ?></b>
        </div>
        <div style="clear:left; margin-top: 10px;">
            <div class="annotation-color" style="background-color:#ad9ee2; width:30px; height:20px; float:left;"></div>
            <b>&nbsp;<?php echo __('Sold Deal'); ?></b>
        </div>
    </div>

    <?php
    $x_unit = 3600 * 24;
    $fromTime = strtotime($deal->getStartTime());
    $toTime = strtotime($deal->getEndTime());
    $currentTime = $helper->getCurrentTime();
    $days = (int) ($toTime - $fromTime) / $x_unit;

    $graph = [];
    $maxQty = 0;
    $total = 0;
    for ($i = -1 ; strtotime(date('Y-m-d 00:00:00', $fromTime + $i * $x_unit)) <= min($toTime + $x_unit, $currentTime + $x_unit); $i++) {
        $thatTime = $fromTime + $x_unit * $i;
        $thatDateBegin = date('Y-m-d 00:00:00', $thatTime);
        $thatDateEnd = date('Y-m-d 23:59:59', $thatTime);
        
        $orderItemCollection = $deal->getOrderItemCollection();
        $orderItemCollection->addFieldToFilter('created_at', ['from'=>$thatDateBegin, 'to'=>$thatDateEnd]);
        $itemQty = 0;
        foreach ($orderItemCollection->getItems() as $item) {
            $itemQty += $item->getQtyOrdered();
        }
        
        if ($itemQty > $maxQty) {
            $maxQty = $itemQty;
        }
        $dayInDeal = (($thatTime > $fromTime) && ($thatTime < $toTime)) ? 1 : 0;
        $graph[] = array('x' => date('m-d', $thatTime), 'y' => $itemQty, 'day_in_deal' => $dayInDeal);
        if ($itemQty) {
            $total += $itemQty;
        }
    }
    ?>

    <canvas id="reportCanvas" height="400" width="920"></canvas>
    <br><br>
    <table style="text-align: left;">
        <tbody>
            <tr><th><?php echo __('Start time'); ?></th><td>&nbsp;<?php echo $deal->getStartTime(); ?></td></tr>
            <tr><th><?php echo __('End time'); ?></th><td>&nbsp;<?php echo $deal->getEndTime(); ?></td></tr>
            <tr><th><?php echo __('Total sales'); ?></th><td>&nbsp;<?php echo $total . __(' item(s)'); ?></td></tr>
        </tbody>
    </table>

    <script type="text/javascript">
        require(['chart'], function () {
            var lineChartData = {
                labels: [
                    // "January","February","March","April","May","June","July"
                    <?php
                    foreach ($graph as $item) {
                        echo '"' . $item['x'] . '",';
                    }
                    ?>
                ],
                datasets: [
                    {
                        fillColor: "rgba(205, 58, 57, 0.2)",
                        strokeColor: "rgba(205, 58, 57, 0.2)",
                        pointColor: "rgba(205, 58, 57, 0.2)",
                        data: [
                            // 28,48,40,19,96,27,100
                            <?php
                            foreach ($graph as $item) {
                                echo ($item['day_in_deal']) ? ($maxQty + 1) . ',' : '0,';
                            }
                            ?>
                        ]
                    },
                    {
                        fillColor: "rgba(100, 100, 236, 0.5)",
                        strokeColor: "rgba(100, 100, 236, 0.9)",
                        pointColor: "rgba(100, 100, 236, 0.9)",
                        data: [
                            // 28,48,40,19,96,27,100
                            <?php
                            foreach ($graph as $item) {
                                echo $item['y'] . ',';
                            }
                            ?>
                        ]
                    },
                ]

            }

            var graph = document.getElementById("reportCanvas").getContext("2d");

            var myLine = new Chart(graph).Line(lineChartData, {
                //Boolean - If we want to override with a hard coded scale
                scaleOverride: true,
                //** Required if scaleOverride is true **
                //Number - The number of steps in a hard coded scale
                scaleSteps: <?php echo $maxQty + 1; ?>,
                //Number - The value jump in the hard coded scale
                scaleStepWidth: 1,
                //Number - The scale starting value
                scaleStartValue: 0,
            });
        });
    </script>

    <?php
}
?>