<!--@copyright Copyright (c) 2016 www.magebuzz.com-->
<?php
$deals = $block->getPagedDeals();
if ($deals->getSize()) {
    $helper = $block->getHelper();
    $limit = $block->getLimit();
    ?>
    <ul class="deal-grid">
        <?php
        foreach ($deals->getItems() as $deal) {
            $deal->load($deal->getId());
            $product = $deal->getProduct();
            if ($product && $product->getId()) {
                $remainQuantity = $deal->getQuantity() - $deal->getSold();
                $productQuantity = $helper->getProductQuantity($product);
                if ($productQuantity <= 0) {
                    $leftText = __('Sorry, this product is sold out!');
                } else if ($remainQuantity < $productQuantity) {
                    $leftText = __('For only ' . $remainQuantity . ' item(s)!');
                } else {
                    $leftText = __('Until Out of Stock');
                }

                $startTime = $helper->getGmtTime(strtotime($deal->getStartTime()));
                ?>
                <li class="item">
                    <a href="<?php echo $product->getProductUrl(); ?>" title="<?php echo $product->getName(); ?>" class="product-image">
                        <img src="<?php echo $helper->getProductImageUrl($product, 'category'); ?>" alt="<?php echo $product->getName() ?>" />
                        <div class="save-price">
                            <div class="price"><?php echo $deal->calSaving(); ?><?php echo __('%'); ?></div>
                        </div>
                    </a>
                    <h4 class="product-name"> 
                        <a href="<?php echo $product->getProductUrl() ?>" title="<?php echo $product->getName() ?>"><?php echo $product->getName() ?></a>
                    </h4>
                    <div class="deal-price">
                        <div class="price-box">
                            <p class="old-price">
                                <span class="price"><?php echo $helper->getPriceWithCurrency($product->getPrice()); ?></span>
                            </p>
                            <p class="special-price">
                                <span class="price"><?php echo $helper->getPriceWithCurrency($deal->getPrice()); ?></span>
                            </p>
                        </div>
                    </div>
                    <h4><?php echo $leftText; ?></h4>
                    <span class="timeleft-coming" data-totime="<?php echo $startTime; ?>"> </span>
                </li>
                <?php
            }
        }
        ?>
    </ul>
    <script type="text/javascript">
        require(['jquery', 'dailydeal_countdown'], function ($) {
            $(document).ready(function () {
                $('.timeleft-coming').dealcountdown();
            });
        });
    </script>
    <?php
    echo $block->getPagerHtml();
    if ($deals->getSize() > $limit) {
        ?>
        <div class="see-all">
            <a href='<?php echo $block->getUrl('dailydeal/index/coming'); ?>'>
                <?php echo __('See all coming deals ...'); ?>
            </a>
        </div>
        <?php
    }
} else {
    ?>
    <p class="note-msg"><?php echo __('There are no deals available.') ?></p>
<?php } ?>
