<!--@copyright Copyright (c) 2016 www.magebuzz.com-->
<?php
$deals = $block->getPagedDeals();
if ($deals->getSize()) {
    $col = 4;
    $helper = $block->getHelper();
    $i = 0;
    foreach ($deals as $deal) {
        $deal->load($deal->getId());
        $product = $deal->getProduct();
        if ($product && $product->getId()) {
            if ($i++ % $col == 0) {
                ?>
                <ul class="deal-grid">
                <?php } ?>
                <li class="item<?php if (($i - 1) % $col == 0) { ?> first<?php } else if ($i % $col == 0) { ?> last<?php } ?>">
                    <a href="<?php echo $product->getProductUrl(); ?>" title="<?php echo $product->getName(); ?>" class="product-image">
                        <img src="<?php echo $helper->getProductImageUrl($product, 'medium'); ?>" alt="<?php echo $product->getName() ?>" width="135"/>
                    </a>
                    <div class="deal-price">
                        <div class="price-box">
                            <p class="old-price">
                                <span class="price"><?php echo $helper->getPriceWithCurrency($product->getPrice()); ?></span>
                            </p>
                            <p class="special-price">
                                <span class="price"><?php echo $helper->getPriceWithCurrency($deal->getPrice()); ?></span>
                            </p>
                        </div>
                        <div class="price-save">
                            <span class="regular-price">
                                <span class="price"><?php echo $deal->calSaving(); ?><?php echo __('%');?></span>
                            </span>
                        </div>
                    </div>
                    <h4 class="product-name"> 
                        <a href="<?php echo $product->getProductUrl() ?>" title="<?php echo $product->getName() ?>"><?php echo $product->getName() ?></a>
                    </h4>
                    <p class="availability out-of-stock"><span><?php echo __('Sorry, this deal was sold out!');?></span></p>
                </li>
                <?php if ($i % $col == 0 || $i == count($deals)) { ?>
                </ul>
                <?php
            }
        }
    }
    echo $block->getPagerHtml();
    ?>
    <br/>
    <!--<script type="text/javascript">decorateGeneric($$('ul.deal-grid'), ['odd', 'even', 'first', 'last'])</script>-->

<?php } else { ?>
    <p class="note-msg"><?php echo __('There are no deals available.') ?></p>
<?php } ?>
