<!--@copyright Copyright (c) 2016 www.magebuzz.com-->
<?php
$limit = $block->getLimit();
$deals = $block->getPreviousDealCollection()->limit($limit);
if ($deals->getSize()) {
    $helper = $block->getHelper();
    $prdCount = 1;
    $isLimit = false;
    ?>
    <ul class="deal-grid">
        <?php
        foreach ($deals->getItems() as $deal) {
            if ($prdCount > $limit) {
                $isLimit = true;
                break;
            }
            $deal->load($deal->getId());
            $productIds = $deal->getProductIds();
            foreach ($productIds as $productId) {
                if ($prdCount > $limit) {
                    $isLimit = true;
                    break;
                }
                $product = $helper->getProductById($productId);
                if ($product && $product->getId()) {
                    $prdCount++;
                    ?>
                    <li class="item">
                        <a href="<?php echo $product->getProductUrl(); ?>" title="<?php echo $product->getName(); ?>" class="product-image">
                            <img src="<?php echo $helper->getProductImageUrl($product, 'category'); ?>" alt="<?php echo $product->getName() ?>" />
                            <div class="save-price">
                                <div class="price"><?php echo $helper->calSaving($product); ?><?php echo __('%'); ?></div>
                            </div>
                        </a>
                        <h4 class="product-name"> 
                            <a href="<?php echo $product->getProductUrl() ?>" title="<?php echo $product->getName() ?>"><?php echo $product->getName() ?></a>
                        </h4>
                        <div class="deal-price">
                            <div class="price-box">
                                <p class="special-price">
                                    <span class="price"><?php echo $helper->getPriceWithCurrency($deal->getPrice()); ?></span>
                                </p>
                                <p class="old-price">
                                    <span class="price"><?php echo $helper->getPriceWithCurrency($product->getPrice()); ?></span>
                                </p>
                            </div>
                        </div>
                        <p class="availability out-of-stock"><span><?php echo __('Sorry, this deal was sold out!'); ?></span></p>
                    </li>
                    <?php
                }
                
            }
            
        }
        ?>
    </ul>
    <?php
    if ($isLimit || $deals->getSize() > $limit) {
        ?>
        <div class="see-all">
            <a href='<?php echo $block->getUrl('dailydeal/index/previous'); ?>'>
                <?php echo __('See all previous deals ...'); ?>
            </a>
        </div>
        <?php
    }
} else {
    ?>
    <p class="note-msg"><?php echo __('There are no deals available.') ?></p>
<?php } ?>
